### PR TITLE
Now, sentinel is compatible with the latest chaincoin's changes

### PR DESCRIPTION
**Pull request by lubuzzo**
- getgovernanceinfo was renamed to getfundinginfo
- There was an JSONRPCException that had an unwanted behavior when 
trying run sentinel into a non-masternode server

### CODE REVIEW

**Comment by HashUnlimited** [comment]
one more thing...
https://github.com/chaincoin/sentinel/blob/43b95deb51d5eed14b8d68ada272e82d94a4e5d6/bin/sentinel.py#L116

**Comment by SmarterHomes** [comment]
we could also bump the version

**Review by SmarterHomes — CHANGES_REQUESTED** [review]
this line needs a fix as well
https://github.com/chaincoin/sentinel/blob/43b95deb51d5eed14b8d68ada272e82d94a4e5d6/bin/sentinel.py#L116

**Comment by lubuzzo** [comment]
Missed that. I will check later.

**Comment by lubuzzo** [comment]
@HashUnlimited isn't necessary change this line, because there are a little hack ( https://github.com/lubuzzo/sentinel/blob/5f07a87a3161647b62019f357bb4e00102ff3eb5/lib/chaincoind.py#L43 )

**Pull request merged**
