### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by seekthex**
Made correction to the install vs the upgrade instructions and changed call from getinfo to getwalletinfo

### CODE REVIEW

**Review by lubuzzo — APPROVED** [review]
Sounds good to me

**Comment by SmarterHomes** [comment]
almost - the getwalletinfo isn't correct there, it should be getnetworkinfo

**Comment by SmarterHomes** [comment]
can we adjust the Contributing part as well in one shot?

**Comment by SmarterHomes** [comment]
all covered by 2c90517 ?

**Comment by lubuzzo** [comment]
@HashUnlimited yes, #3 covered all.

@seekthex You can close this PR.

**Pull request closed without merging**
